---
config:
  flowchart:
    curve: linear
---
graph TD;
	__start__([<p>__start__</p>]):::first
	extract_one(extract_one)
	collect_invoices(collect_invoices)
	validate_invoices(validate_invoices)
	lookup_taxpayer(lookup_taxpayer)
	analyze_income(analyze_income)
	request_accountant_review(request_accountant_review)
	write_report(write_report)
	__end__([<p>__end__</p>]):::last
	__start__ -.-> collect_invoices;
	__start__ -.-> extract_one;
	analyze_income -. &nbsp;review&nbsp; .-> request_accountant_review;
	analyze_income -. &nbsp;ok&nbsp; .-> write_report;
	collect_invoices --> validate_invoices;
	extract_one --> collect_invoices;
	lookup_taxpayer --> analyze_income;
	request_accountant_review --> write_report;
	validate_invoices --> lookup_taxpayer;
	write_report --> __end__;
	classDef default fill:#f2f0ff,line-height:1.2
	classDef first fill-opacity:0
	classDef last fill:#bfb6fc
